<?php 

//curl query for SOASTA
// Report all PHP errors
error_reporting(-1);

//Check if there is an open session, if not, then create one
if(!file_exists('./_sessions/session_lock.lock')){
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://mpulse.soasta.com/concerto/services/rest/RepositoryService/v1/Tokens");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"userName\":\"user123\", \"password\":\"Password123\"}");
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");

$headers = array();
$headers[] = "Content-Type: application/x-www-form-urlencoded";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

echo $result;

//Lets create a hardlock on the sessions used, this is to spare the permissable rate of API usage
//This file gets deleted every $interval time

$ourFileName = "./_sessions/session_lock.lock";
$ourFileHandle = fopen($ourFileName, 'w') or die("can't open file");
fclose($ourFileHandle);

//Lets write the SOASTA Authentication key to file(very dangerous, be carefule)
//We will write to session.lock file for now, then log a stale file that wont be deleted to _sessions folder
file_put_contents($ourFileName, $result);

$ourFileName = "./_sessions/session_".$result;
$ourFileHandle = fopen($ourFileName, 'w') or die("can't open file");
fclose($ourFileHandle);

} else {
    echo 'Session in play'; 
    }

// Lets expire the file after 5 hours for session handling
$dir = getcwd()."/_sessions/";//dir absolute path
$interval = strtotime('- 5 minutes');//files older than 24hours

foreach (glob($dir."session_lock.lock") as $file) 
    //delete if older
    if (filemtime($file) <= $interval ) unlink($file);

//Lets get session token if its still valid
//$session_content = file_get_contents(getcwd()'./sessions/session_lock.lock');
//echo $session_content;



